// Generated by CoffeeScript 1.7.1
(function() {
  var LocalVariableBehavior, ScriptingContainer, Semaphore, System, Thread,
    __slice = [].slice;

  System = java.lang.System;

  Thread = java.lang.Thread;

  Semaphore = java.util.concurrent.Semaphore;

  ScriptingContainer = Packages.org.jruby.embed.ScriptingContainer;

  LocalVariableBehavior = org.jruby.embed.LocalVariableBehavior;

  this.Ruby = function() {
    var ruby, rubyMutex, scriptingContainer;
    rubyMutex = new Semaphore(1);
    scriptingContainer = new ScriptingContainer(LocalVariableBehavior.PERSISTENT);
    ruby = function(code) {
      var result;
      rubyMutex.acquire();
      result = scriptingContainer.runScriptlet(code);
      rubyMutex.release();
      return result;
    };
    ruby.setGemHome = function(gemHome) {
      return ruby("ENV['GEM_HOME'] = " + gemHome);
    };
    ruby.preload = function() {
      var gems, requireThread, script;
      gems = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (gems.length >= 1) {
        script = gems.slice(1, +gems.length + 1 || 9e9).reduce((function(p, c) {
          return "" + p + "; require '" + c + "'";
        }), "require '" + gems[0] + "'");
      } else {
        script = "";
      }
      requireThread = new Thread(function() {
        rubyMutex.acquire();
        scriptingContainer.runScriptlet(script);
        return rubyMutex.release();
      });
      return requireThread.start();
    };
    return ruby;
  };

}).call(this);
