// Generated by CoffeeScript 1.7.1
(function() {
  var LocalContextScope, LocalVariableBehavior, RuntimeState, ScriptingContainer, Semaphore, System, Thread, global, runtimeState, scriptingContainer,
    __slice = [].slice;

  System = java.lang.System;

  Thread = java.lang.Thread;

  Semaphore = java.util.concurrent.Semaphore;

  ScriptingContainer = Packages.org.jruby.embed.ScriptingContainer;

  LocalVariableBehavior = org.jruby.embed.LocalVariableBehavior;

  LocalContextScope = org.jruby.embed.LocalContextScope;

  global = this;

  scriptingContainer = new ScriptingContainer(LocalContextScope.CONCURRENT, LocalVariableBehavior.PERSISTENT);

  RuntimeState = {
    UNLOADED: 0,
    LOADING: 1,
    LOADED: 2,
    FAILED: 3
  };

  runtimeState = RuntimeState.UNLOADED;

  global.Ruby = function() {
    var ruby;
    ruby = function(code) {
      var result;
      switch (runtimeState) {
        case RuntimeState.UNLOADED:
          throw 'Must call Ruby.preload([gems]) exactly once before executing ruby code';
          break;
        case RuntimeState.LOADING:
          while (runtimeState === RuntimeState.LOADING) {
            Thread.sleep(100);
          }
          return ruby(code);
        case RuntimeState.FAILED:
          throw 'Ruby runtime failed to load.';
          break;
        case RuntimeState.LOADED:
          result = scriptingContainer.runScriptlet(code);
          return result;
      }
    };
    ruby.setGemHome = function(gemHome) {
      return ruby("ENV['GEM_HOME'] = " + gemHome);
    };
    return ruby;
  };

  global.Ruby.preload = function() {
    var gems, script;
    gems = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    runtimeState = RuntimeState.LOADING;
    if (gems.length >= 1) {
      script = gems.slice(1, +gems.length + 1 || 9e9).reduce((function(p, c) {
        return "" + p + "; require '" + c + "'";
      }), "require '" + gems[0] + "'");
    } else {
      script = "nil";
    }
    return (new Thread(function() {
      var ex;
      try {
        if (runtimeState === RuntimeState.LOADED) {
          return;
        }
        scriptingContainer.runScriptlet(script);
        return runtimeState = RuntimeState.LOADED;
      } catch (_error) {
        ex = _error;
        runtimeState = RuntimeState.FAILED;
        throw ex;
      }
    })).start();
  };

}).call(this);
